[project]
name = "website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "ipykernel>=6.29.5",
    "ipython>=9.2.0",
    "pandas>=2.2.3",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.2",
]
